### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by maciek-jk** [vanstorm9/yugioh-one-shot-learning#1]
Hello, I have trouble running this program with my own image set, would you mind including a short instruction in the readme how to run it (which files to run, etc.).
Also, can you include a requirements.txt file with packages needed?

**Comment by vanstorm9** [comment]
Python command instructions were added to the readme as well as adding requirements.txt to the repo.

You must have you imageset directory in this format:
-cardDatabaseFull
----cardname1
--------cardname1.png
----cardname2
--------cardname2.png
----cardname3
--------cardname3.png

**Comment by maciek-jk** [comment]
I think something still might be missing from the requirements.txt, I get this error on running train.py `ModuleNotFoundError: No module named 'models_lpf'
`

**Comment by vanstorm9** [comment]
Ah I see, I just did a git push of the 'models_lpf' scripts into the repo. You should be able to run the script now

**Comment by maciek-jk** [comment]
Thanks, that fixed it, but now running to new errors.
`Traceback (most recent call last):
  File "predict.py", line 41, in <module>
    assert os.path.exists(loadPath)
AssertionError
`
seems its these two files that are missing hardcoded in the predict.py
`loadPath = './savedModels/res-withShift-150-072020.pth'


assert os.path.exists(loadPath)


dictPath = './savedModels/featureMap-withShift-150-072020.pkl'

assert os.path.exists(dictPath)
`

**Comment by vanstorm9** [comment]
Download it from this link:
https://drive.google.com/drive/folders/1JZCt7hHf4NYgEp2XiE1SpNboAbgBxwDY?usp=sharing
